### ISSUE TITLE
BUG: Prepends additional task number 

### ISSUE THREAD

**Issue by ivysochyn** [avilaton/add-msg-issue-prefix-hook#16]
Problem
------------
Consider case when you have to  mark commit with different task number from one in branch name. Even though message containing proper task number was passed before hook invocation, `add-msg-issue-prefix` hook still prepends task handle which then should be manually removed.

Possible solution I see
------------
I suggest adding a check whether commit message already contains issue number by utilizing template to render ticket id.

**Comment by avilaton** [comment]
I think we had that a while back. Maybe it disappeared with recent changes. Feel free to send a PR to do it if you find the time.

**Comment by ivysochyn** [comment]
Added PR #17 with changes present. Ready for review.

**Comment by ivysochyn** [comment]
Changes were reviewed and merged. Closing the issue.
