### ISSUE TITLE
FEATURE: Auto `--sign-off` commits

### ISSUE THREAD

**Issue by ivysochyn** [avilaton/add-msg-issue-prefix-hook#18]
Currently, `git` doesn't allow to configure automatically DCO sign off of commits. To my opinion, we could add separate hook in same repository responsible for signing off commit if author's signature doesn't exist.

What do you think?

**Comment by avilaton** [comment]
No idea, I don't use that, sorry

**Comment by ivysochyn** [comment]
Closing the issue as irrelevant.
